/**
 * Generated by tsnapi — public API snapshot of `@mcbe-mods/ipc`
 */
// #region Interfaces
export interface DataCompressor {
  compress: (_: string) => string;
  decompress: (_: string) => string;
}
export interface Deserializer<T> {
  deserialize: (_: string) => T;
}
export interface IPCEvents {
  [EVENTS.ERROR]: Error;
}
export interface IPCOptions {
  namespace?: string;
  chunkSize?: number;
  compressThreshold?: number;
  compress?: DataCompressor;
  maxPacketSize?: number;
  chunkTimeout?: number;
  cipher?: ProtocolCipher$1;
}
export interface OnOptions<T = never> {
  deserializer?: Deserializer<T>;
}
export interface SendOptions<T = never> {
  serializer?: Serializer<T>;
}
export interface Serializer<T> {
  serialize: (_: T) => string;
}
// #endregion

// #region Classes
export declare class Chunker {
  #private;
  constructor(_: number);
  split(_: string): Array<{
    seq: number;
    total: number;
    data: string;
  }>;
  assemble(_: string, _: number, _: number, _: string, _: boolean, _?: number): {
    done: false;
  } | {
    done: true;
    data: string;
    compressed: boolean;
  };
  get pendingCount(): number;
}
export declare class IPC {
  #private;
  readonly events: EventEmitter<IPCEvents>;
  constructor(_?: IPCOptions);
  dispose(): void;
  send(_: string): void;
  send<T>(_: string, _: T): void;
  send<T>(_: string, _: T, _: SendOptions<T>): void;
  on<T>(_: string, _: (_: T) => void): () => void;
  on<T>(_: string, _: (_: T) => void, _: OnOptions<T>): () => void;
  once<T>(_: string, _: (_: T) => void): () => void;
}
// #endregion

// #region Variables
export declare const EVENTS: {
  readonly ERROR: "error";
};
export declare const PROTOCOL_VERSION: "1";
// #endregion

// #region Other
export { ProtocolCipher }
// #endregion